### ISSUE TITLE
Migration Error

### ISSUE THREAD

**Issue by okwme** [gjeanmart/stackexchange#1]
Thanks for creating this repo. I had a similar set up based on [the truffle tutorial](http://truffleframework.com/tutorials/using-infura-custom-provider)

I've been getting this error with your code and the code from the truffle doc: 
````
$ truffle compile && truffle migrate --reset --network ropsten
(node:38919) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: this.provider.sendAsync is not a function
(node:38919) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:38920) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: this.provider.sendAsync is not a function
(node:38920) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Using network 'ropsten'.

Running migration: 1_initial_migration.js
````

i've added to the issue on the truffle issue tracker [here](https://github.com/trufflesuite/trufflesuite.github.io/issues/165), do you know where this error could be coming from?

**Comment by okwme** [comment]
found one solution is to install older versions of the packages:
$ npm install ethereumjs-wallet bip39 web3-provider-engine@8.6.1 web3@0.18.4 zeppelin-solidity --save

**Comment by gjeanmart** [comment]
Thanks @okwme ! I updated the code
